version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: job
    ports:
      - '5432:5432'
  application:
    image: find-job-app
    container_name: find-job-app
    build: ./
    depends_on:
      - postgres
    ports:
      - '8080:8080'







