spring:
  jpa:
    hibernate:
      ddl-auto: none
  jwt:
    secret: 12312321k3ksadas942232332
    expiration: 7200
  liquibase:
    enabled: true
    change-log: classpath:/changelog.xml
  profiles:
    active: test

