spring:
  jpa:
    hibernate:
      ddl-auto: none
  jwt:
    secret: 12312321k3ksadas942232332dsjhnfbdsiouhfsopuhf9p248hr92348her239eh239phe13pu9eh1ijxndin13idjsb319upeb319eub13beu9139ubsd139uodeb319uoe13e9
    expiration: 7200
  liquibase:
    enabled: true
    change-log: classpath:/changelog.xml
  datasource:
#      url: jdbc:postgresql://postgres:5432/job
      url: jdbc:postgresql://localhost:5432/job
      username: admin
      password: password


