ALTER TABLE ROLE
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE CUSTOM_USER
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE EMPLOYER
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE EMPLOYEE
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE COMPANY
ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE ADDRESS
ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE ADMIN
ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE CATEGORY
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE EMPLOYMENT
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE SENIORITY
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE ADVERTISEMENT
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE ADVERTISEMENT_EMPLOYMENT_TYPE
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE ADVERTISEMENT_SENIORITY_LEVEL
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE REQUIREMENT
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE ADVERTISEMENT_LOCATION
ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE BENEFIT
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE APPLICANT
ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE COMPANY_LOCATION
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE COMPANY_CATEGORIES
ALTER COLUMN id SET DEFAULT gen_random_uuid();


ALTER TABLE USER_ROLES
ALTER COLUMN id SET DEFAULT gen_random_uuid();

